[program:xvfb]
command=/usr/bin/Xvfb :99 -screen 0 %(ENV_DISPLAY_WIDTH)sx%(ENV_DISPLAY_HEIGHT)sx%(ENV_DISPLAY_DEPTH)s
autorestart=true
priority=10
stdout_logfile=/logs/xvfb.log
stderr_logfile=/logs/xvfb.err
